version: '3.3'

services:
   db:
     image: maurofelipe/percona:5.7-v1.1
     ports: 
       - "3306:3306"
     volumes:
       - ./dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db_wordpress
       MYSQL_USER: uap_wordpress
       MYSQL_PASSWORD: uap_password

   redis:
     image: maurofelipe/redis:3.2.11-v1.0
     ports:
       - "6379:6379"
     restart: always

   wordpress:
     depends_on:
       - db
       - redis
     image: maurofelipe/wordpress:4.9.4-php7.2-apache-redis-v1.0
     ports:
       - "80:80"
     restart: always
     volumes:
       - ./wwwdata:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: uap_wordpress
       WORDPRESS_DB_PASSWORD: uap_password
       WORDPRESS_DB_NAME: db_wordpress
volumes:
    dbdata:
    wwwdata:
